// PATH: app/api/qa-insight/route.js
import Anthropic from '@anthropic-ai/sdk';

export const dynamic = 'force-dynamic';

async function slackPost(text, blocks) {
  const res = await fetch('https://slack.com/api/chat.postMessage', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${process.env.SLACK_BOT_TOKEN}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      channel: 'health-ops',   // ← your channel
      text,
      blocks,
    }),
  });
  return res.json();
}

export async function POST(request) {
  try {
    const { aggregations, total, date_range, send_to_slack } = await request.json();

    if (!aggregations || total === 0) {
      return Response.json({ error: 'No data to analyse' }, { status: 400 });
    }

    // ── Build prompt ──────────────────────────────────────────────────
    const dateLabel = date_range?.from === date_range?.to
      ? `On ${date_range?.from}`
      : `From ${date_range?.from} to ${date_range?.to}`;

    const summaryLines = Object.entries(aggregations.by_issue || {})
      .sort((a, b) => b[1] - a[1])
      .map(([type, count]) => `- ${type}: ${count}`)
      .join('\n');

    const insurerLines = Object.entries(aggregations.by_insurer || {})
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5)
      .map(([insurer, count]) => `- ${insurer}: ${count} flags`)
      .join('\n');

    const providerLines = Object.entries(aggregations.by_provider || {})
      .sort((a, b) => b[1] - a[1])
      .slice(0, 3)
      .map(([provider, count]) => `- ${provider}: ${count} flags`)
      .join('\n');

    const prompt = `You are a senior health insurance QA analyst for Curacel, an AI-powered insurance infrastructure company operating across African markets.

${dateLabel}, ${total} QA flags were raised with the following breakdown:

Issue Types:
${summaryLines || 'No breakdown available'}

Top Insurers by flags:
${insurerLines || 'No breakdown available'}

Top Flagged Providers:
${providerLines || 'No breakdown available'}

Write a concise, sharp, operational QA intelligence brief (3-5 sentences max). Lead with the most significant finding. Identify any patterns suggesting systemic issues. End with one specific, actionable recommended next step. Be direct, factual, and use precise numbers. Do not add markdown headers or bullet points — write in flowing prose.`;

    // ── Call Anthropic ────────────────────────────────────────────────
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
    const message = await client.messages.create({
      model: 'claude-opus-4-5',
      max_tokens: 300,
      messages: [{ role: 'user', content: prompt }],
    });

    const insight = message.content[0]?.text || 'Unable to generate insight.';

    // ── Send to Slack if requested ────────────────────────────────────
    if (send_to_slack) {
      const dateStr = date_range?.from === date_range?.to
        ? date_range?.from
        : `${date_range?.from} → ${date_range?.to}`;

      const slackResult = await slackPost(
        `🚩 QA Intelligence Brief — ${dateStr}`,
        [
          {
            type: 'header',
            text: { type: 'plain_text', text: `🚩 QA Intelligence Brief`, emoji: true },
          },
          {
            type: 'context',
            elements: [{ type: 'mrkdwn', text: `📅 *${dateStr}*  ·  ${total} total flags` }],
          },
          { type: 'divider' },
          {
            type: 'section',
            text: { type: 'mrkdwn', text: insight },
          },
          { type: 'divider' },
          {
            type: 'context',
            elements: [{
              type: 'mrkdwn',
              text: `🤖 AI-generated by Claims Intel  ·  <https://claims-dashboard.vercel.app/qa|View QA Dashboard →>`,
            }],
          },
        ]
      );

      if (!slackResult.ok) {
        console.error('[qa-insight] Slack error:', slackResult.error);
        // Return insight anyway even if Slack fails
        return Response.json({ insight, slack_error: slackResult.error });
      }
    }

    return Response.json({ insight });

  } catch (err) {
    console.error('[qa-insight error]', err.message);
    return Response.json({ error: err.message }, { status: 500 });
  }
}
