// PATH: app/api/qa-insight/route.js
import Anthropic from '@anthropic-ai/sdk';
import { getSettings } from '../../lib/settings';

export const dynamic = 'force-dynamic';

async function slackPost(channel, text, blocks) {
  const res = await fetch('https://slack.com/api/chat.postMessage', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${process.env.SLACK_BOT_TOKEN}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ channel, text, blocks }),
  });
  return res.json();
}

export async function POST(request) {
  try {
    const { aggregations, total, date_range, send_to_slack, detail } = await request.json();

    if (!aggregations || total === 0) {
      return Response.json({ error: 'No data to analyse' }, { status: 400 });
    }

    // ── Build prompt ──────────────────────────────────────────────────
    const dateLabel = date_range?.from === date_range?.to
      ? `On ${date_range?.from}`
      : `From ${date_range?.from} to ${date_range?.to}`;

    // aggregations are arrays of objects: [{ issue, count }], [{ insurer, count }], [{ provider_name, count }]
    const summaryLines = (aggregations.by_issue || [])
      .slice(0, 8)
      .map(r => `- ${r.issue}: ${r.count}`)
      .join('\n');

    const insurerLines = (aggregations.by_insurer || [])
      .slice(0, 5)
      .map(r => `- ${r.insurer}: ${r.count} flags`)
      .join('\n');

    const providerLines = (aggregations.top_providers || [])
      .filter(r => {
        const n = r.provider_name || r.provider || r.name || '';
        return n && n.toLowerCase() !== 'undefined' && n.toLowerCase() !== 'null';
      })
      .slice(0, 3)
      .map(r => `- ${r.provider_name || r.provider || r.name}: ${r.count} flags`)
      .join('\n');

    const prompt = `You are a senior health insurance QA analyst for Curacel, an AI-powered insurance infrastructure company operating across African markets.

${dateLabel}, ${total} QA flags were raised with the following breakdown:

Issue Types:
${summaryLines || 'No breakdown available'}

Top Insurers by flags:
${insurerLines || 'No breakdown available'}

Top Flagged Providers:
${providerLines || 'No breakdown available'}

${detail === 'detailed' ? 'Write a detailed QA intelligence report (6-8 sentences). Cover: (1) overall flag volume and trend, (2) top 2-3 issue types with specific counts and percentages, (3) most affected insurers or providers, (4) patterns suggesting systemic issues, (5) risk assessment, (6) two specific recommended actions. Be direct and data-driven. No markdown. No bullets. Plain prose only.' : 'Write a concise QA intelligence brief (3-5 sentences). Lead with the most significant finding. Identify patterns suggesting systemic issues. End with one specific actionable next step. Be direct, factual, precise numbers. No markdown. No bullets. Plain prose only.'}\`;

    // ── Call Anthropic ────────────────────────────────────────────────
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
    const message = await client.messages.create({
      model: 'claude-opus-4-5',
      max_tokens: 300,
      messages: [{ role: 'user', content: prompt }],
    });

    const insight = message.content[0]?.text || 'Unable to generate insight.';

    // ── Send to Slack if requested ────────────────────────────────────
    if (send_to_slack) {
      const dateStr = date_range?.from === date_range?.to
        ? date_range?.from
        : `${date_range?.from} → ${date_range?.to}`;

      const cfg = await getSettings();
      const qaChannel = cfg('slack_channel_qa_insight', 'C03TBH0RL76');
      const featureSlack = cfg('feature_slack_sends', 'true');
      if (featureSlack === 'false') {
        return Response.json({ insight, slack_error: 'slack_disabled_by_settings' });
      }
      const slackResult = await slackPost(
        qaChannel,
        `🚩 QA Intelligence Brief — ${dateStr}`,
        [
          {
            type: 'header',
            text: { type: 'plain_text', text: `🚩 QA Intelligence Brief`, emoji: true },
          },
          {
            type: 'context',
            elements: [{ type: 'mrkdwn', text: `📅 *${dateStr}*  ·  ${total} total flags` }],
          },
          { type: 'divider' },
          {
            type: 'section',
            text: { type: 'mrkdwn', text: insight },
          },
          { type: 'divider' },
          {
            type: 'context',
            elements: [{
              type: 'mrkdwn',
              text: `🤖 AI-generated by Claims Intel  ·  <https://claims-dashboard.vercel.app/qa|View QA Dashboard →>`,
            }],
          },
        ]
      );

      if (!slackResult.ok) {
        console.error('[qa-insight] Slack error:', slackResult.error);
        return Response.json({ insight, slack_error: slackResult.error });
      }

      // Return ts + channel so frontend can show Undo/Delete button
      return Response.json({
        insight,
        slack_sent: true,
        slack_ts: slackResult.ts,
        slack_channel: qaChannel,
      });
    }

    return Response.json({ insight });

  } catch (err) {
    console.error('[qa-insight error]', err.message);
    return Response.json({ error: err.message }, { status: 500 });
  }
}
