// app/api/ops-narrative/route.js
import Anthropic from '@anthropic-ai/sdk';
import { getSettings } from '../../lib/settings';

export const dynamic = 'force-dynamic';

export async function POST(request) {
  try {
    const data = await request.json();
    const { submission, targets, kpis, today_vs_yesterday, week_vs_lastweek, send_to_slack, insight: prebuilt, detail } = data;

    const pending   = submission?.pending || [];
    const submitted = submission?.submitted || 0;
    const total     = submission?.total || 0;

    const instruction = detail === 'detailed'
      ? 'Write a detailed operational intelligence report (6-8 sentences). Cover: (1) team submission status, (2) target performance with specific numbers, (3) key metric trends vs yesterday and last week, (4) risks or concerns, (5) two specific recommended actions. No bullet points. No markdown. Plain sentences only.'
      : 'Write a concise 2-3 sentence operational intelligence summary. Lead with the most urgent issue. Mention specific numbers. End with one clear recommended action. No bullet points. No markdown. Plain sentences only.';

    // If we already have the insight (Slack send after generate), skip AI call
    let insight = prebuilt;

    if (!insight) {
      const prompt = `You are the operations intelligence system for Curacel Health Ops, an African health insurance claims processing team.

Here is today's operational data:

TEAM SUBMISSIONS:
- ${submitted} of ${total} members have submitted reports today
- Pending: ${pending.length > 0 ? pending.join(', ') : 'None — all submitted'}
- Submission rate: ${kpis?.submission_rate ?? 0}%

TARGETS (${targets?.length || 0} active):
${(targets || []).map(t => `- ${t.name}: ${t.pct_complete ?? 0}% complete, pace: ${t.pace}, ${t.days_left}d left`).join('\n') || '- No active targets'}

TODAY VS YESTERDAY:
${(today_vs_yesterday || []).filter(m => m.today > 0 || m.yesterday > 0).map(m => `- ${m.label}: ${m.today?.toLocaleString()} today vs ${m.yesterday?.toLocaleString()} yesterday (${m.pct_change !== null ? (m.pct_change > 0 ? '+' : '') + m.pct_change + '%' : 'n/a'})`).join('\n') || '- No data'}

THIS WEEK VS LAST WEEK:
${(week_vs_lastweek || []).filter(m => m.this_week > 0 || m.last_week > 0).map(m => `- ${m.label}: ${m.this_week?.toLocaleString()} this week vs ${m.last_week?.toLocaleString()} last week`).join('\n') || '- No data'}

${instruction}`;

      const client  = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
      const message = await client.messages.create({
        model:      'claude-sonnet-4-20250514',
        max_tokens: 400,
        messages:   [{ role: 'user', content: prompt }],
      });
      insight = message.content[0].text;
    }

    // Send to Slack if requested
    if (send_to_slack) {
      const cfg         = await getSettings();
      const channel     = cfg('slack_channel_health_ops', 'C0ALCPCE9FZ');
      const featureSlack = cfg('feature_slack_sends', 'true');

      if (featureSlack === 'false') {
        return Response.json({ insight, slack_error: 'slack_disabled_by_settings' });
      }

      const today = new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' });

      const slackRes = await fetch('https://slack.com/api/chat.postMessage', {
        method:  'POST',
        headers: { 'Authorization': `Bearer ${process.env.SLACK_BOT_TOKEN}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          channel,
          text: `Ops Intelligence - ${today}`,
          blocks: [
            { type: 'header', text: { type: 'plain_text', text: 'Operations Intelligence Brief', emoji: true } },
            { type: 'context', elements: [{ type: 'mrkdwn', text: `*${today}*  |  ${submitted}/${total} members submitted  |  ${kpis?.submission_rate ?? 0}% submission rate` }] },
            { type: 'divider' },
            { type: 'section', text: { type: 'mrkdwn', text: insight } },
            { type: 'divider' },
            { type: 'context', elements: [{ type: 'mrkdwn', text: `AI-generated by Claims Intel | <https://claims-dashboard.vercel.app/ops|View Ops Overview>` }] },
          ],
        }),
      });

      const slackData = await slackRes.json();
      if (!slackData.ok) {
        console.error('[ops-narrative] Slack error:', slackData.error);
        return Response.json({ insight, slack_error: slackData.error });
      }

      return Response.json({ insight, slack_sent: true, slack_ts: slackData.ts, slack_channel: channel });
    }

    return Response.json({ insight });

  } catch (err) {
    console.error('[ops-narrative]', err);
    return Response.json({ error: err.message }, { status: 500 });
  }
}
